// Prompt Archive 2004 - outfit data and compatibility rules
const outfitColors=["black","white","brown","blue","pink","gray","red","green","purple","beige"];

const styles = {
  y2k:{name:"y2k streetwear",sil:["baggy layered silhouette","cropped top-heavy silhouette","relaxed low-rise silhouette","slim sporty silhouette"],
    tops:["oversized zip hoodie","cropped bomber jacket","layered tank top","technical track jacket","cropped jersey jacket","boxy zip cardigan"],
    bottoms:["baggy cargo pants","wide cargo shorts","pleated mini skirt","low-rise wide jeans","layered shorts","utility mini skirt"],
    shoes:["chunky platform sneakers","oversized sneakers","platform skate shoes","thick sole trainers"],
    extras:["crossbody pouch","hanging belt straps","arm warmers","double belt","zipper details","star charms","mini shoulder bag","wallet chain"]},
  soft:{name:"soft grunge fashion",sil:["drooping layered silhouette","slouchy oversized silhouette","soft compact silhouette","long cozy silhouette"],
    tops:["distressed knit sweater","oversized cardigan jacket","washed zip hoodie","layered knit top","cropped knit bolero","slouchy hooded sweater"],
    bottoms:["layered mini skirt","loose shorts","wide distressed pants","pleated skirt","scrunched shorts","soft utility skirt"],
    shoes:["heavy platform shoes","scrunched leg warmer boots","chunky sneakers","soft platform boots"],
    extras:["chain charms","loose socks","leg warmers","mini shoulder bag","stitched details","safety pin accents","fabric straps","tiny heart hardware"]},
  cyber:{name:"cyber y2k streetwear",sil:["sharp cropped silhouette","technical baggy silhouette","fitted top-heavy silhouette","segmented layered silhouette"],
    tops:["cropped technical jacket","fitted zip top","structured cyber jacket","mesh layered top","paneled utility top","cropped shell jacket"],
    bottoms:["strapped cargo pants","asymmetrical mini skirt","technical shorts","wide utility pants","modular skirt panels","low-rise tech trousers"],
    shoes:["futuristic platform sneakers","knee-high technical boots","heavy platform boots","segmented sole sneakers"],
    extras:["cable details","utility straps","metal rings","micro pouches","visor hardware","clip fasteners","device holster","clear panel accents"]},
  metal:{name:"metallic cyber gothic fashion",sil:["sharp fitted silhouette","armored top-heavy silhouette","sculpted asymmetric silhouette","heavy lower-body silhouette"],
    tops:["sculpted gothic bodice","glossy fitted jacket","armored corset-inspired top","structured cutout top","paneled gothic bustier","cropped armored bolero"],
    bottoms:["asymmetrical strapped skirt","fitted shorts with harness straps","layered armor skirt","low-rise strapped pants","ring-belt mini skirt","paneled gothic shorts"],
    shoes:["massive platform boots","heavy combat platform boots","knee-high futuristic boots","armored platform shoes"],
    extras:["ring hardware","chain harness","spiked details","metal plates","oversized buckles","industrial clips","segmented armor pieces","body straps"]},
  aviator:{name:"aviator streetwear",sil:["bulky cropped flight silhouette","cozy utility silhouette","relaxed layered silhouette","top-heavy pilot silhouette"],
    tops:["cropped flight jacket","distressed flight jacket","fur-trimmed aviator jacket","knit flight layer","oversized bomber vest","utility pilot jacket"],
    bottoms:["loose aviation pants","cargo shorts","utility trousers","layered shorts","strapped flight pants","thick cuff shorts"],
    shoes:["aviator boots","heavy winter boots","chunky utility boots","thick pilot boots"],
    extras:["pilot straps","utility belt","crossbody map pouch","fingerless gloves","buckle details","patch pockets","flight harness","long belt tails"]},
  animal:{name:"plush animal streetwear",sil:["puffy compact silhouette","oversized cozy silhouette","long drooping silhouette","rounded layered silhouette"],
    tops:["oversized animal hoodie","fur-trimmed jacket","puffy zip jacket","soft oversized sweater","plush shell jacket","cropped fluffy hoodie"],
    bottoms:["baggy shorts","rounded mini skirt","loose cargo pants","layered shorts","puffy skirt","soft cuff trousers"],
    shoes:["oversized plush boots","chunky sneakers","thick winter boots","rounded platform shoes"],
    extras:["plush pouch","fluffy leg warmers","soft mittens","dangling charms","stitched details","paw-shaped pouch","round utility bag","soft straps"]},
  angel:{name:"cyber angel streetwear",sil:["sleek fitted silhouette","floating layered silhouette","sharp asymmetric silhouette","light top-heavy silhouette"],
    tops:["fitted harness top","cropped technical jacket","structured bolero","layered zip top","wing-mount bodice","segmented cropped jacket"],
    bottoms:["asymmetrical mini skirt","strapped shorts","fitted cargo pants","layered skirt","floating panel skirt","ring-linked shorts"],
    shoes:["platform boots","futuristic knee boots","angular platform shoes","segmented high boots"],
    extras:["back harness","floating ornaments","metal rings","thigh straps","transparent details","star hardware","segmented straps","waist clips"]},
  doll:{name:"cyber doll gothic fashion",sil:["compact doll silhouette","fitted waist silhouette","puffy top-balanced silhouette","rounded skirt silhouette"],
    tops:["corset-inspired bodice","cropped puff-sleeve jacket","fitted ribbon top","structured doll jacket","lace-up cropped top","mini bolero jacket"],
    bottoms:["layered mini skirt","bubble skirt","pleated strapped skirt","fitted shorts","tiered skirt","garter-linked mini skirt"],
    shoes:["doll platform boots","thick buckle shoes","knee-high platform boots","rounded platform shoes"],
    extras:["oversized bows","garter straps","heart hardware","lace details","miniature charms","ribbon belts","tiny lock charms","frill trim"]},
  webcore:{name:"webcore fashion",sil:["graphic baggy silhouette","tech layered silhouette","compact digital silhouette","boxy screen-inspired silhouette"],
    tops:["oversized graphic hoodie","layered mesh zip top","cropped utility jacket","technical sweatshirt","window-panel jacket","boxy track top"],
    bottoms:["baggy utility pants","wide shorts","layered mini skirt","strapped cargo pants","pixel-pocket trousers","paneled shorts"],
    shoes:["chunky tech sneakers","platform sneakers","utility boots","retro runner platforms"],
    extras:["digital charms","cable straps","pixel accessories","mini device pouch","glitch motifs","screen-shaped pouch","disc charm","folder-shaped bag"]},
  winter:{name:"winter utility streetwear",sil:["bulky layered winter silhouette","soft oversized silhouette","heavy bottom silhouette","compact insulated silhouette"],
    tops:["cropped puffer jacket","oversized insulated jacket","fur-trimmed zip jacket","thick knit utility top","short padded coat","layered fleece jacket"],
    bottoms:["baggy winter cargo pants","padded shorts","utility mini skirt","thick cuff trousers","layered winter shorts","strap cargo skirt"],
    shoes:["oversized winter boots","fur-lined platform boots","chunky snow boots","thick utility boots"],
    extras:["thick leg warmers","padded gloves","utility pouch","wide scarf","buckle straps","soft harness","thermal sleeves","mini thermos pouch"]},
  sport:{name:"sport tech y2k fashion",sil:["athletic fitted silhouette","sporty oversized silhouette","cropped technical silhouette","balanced track silhouette"],
    tops:["cropped track jacket","technical jersey top","zip athletic shell","short racing jacket","panelled sport hoodie","mesh utility top"],
    bottoms:["track shorts","low-rise cargo pants","sport mini skirt","paneled jogger pants","fitted utility shorts","wide track pants"],
    shoes:["chunky running platforms","technical sneakers","oversized trainers","sport platform shoes"],
    extras:["wrist bands","utility clips","micro sport bag","zip details","number patches","headband accessory","sport straps","device pouch"]},
  mcbling:{name:"mcbling y2k fashion",sil:["fitted glam silhouette","tiny-top wide-bottom silhouette","cropped diva silhouette","low-rise flashy silhouette"],
    tops:["fitted zip jacket","cropped faux-fur jacket","rhinestone tank top","shrunken track jacket","halter-style layered top","short glam cardigan"],
    bottoms:["low-rise flared pants","micro pleated skirt","wide velour pants","fitted shorts","denim mini skirt","low-rise cargo skirt"],
    shoes:["platform sneakers","chunky glam boots","thick sole trainers","knee-high platform boots"],
    extras:["rhinestone details","heart charm belt","mini shoulder bag","phone charm","glossy hardware","oversized sunglasses accessory","chain belt","star jewelry"]},
  acubi:{name:"acubi tech fashion",sil:["minimal fitted silhouette","slim layered silhouette","cropped clean silhouette","narrow technical silhouette"],
    tops:["fitted bolero top","cropped zip cardigan","layered fitted tank","minimal technical top","short shrug jacket","asymmetrical fitted top"],
    bottoms:["low-rise straight pants","fitted cargo skirt","slim utility trousers","layered mini skirt","straight cargo pants","fitted shorts"],
    shoes:["minimal platform sneakers","slim technical boots","chunky low-profile sneakers","platform loafers"],
    extras:["thin utility straps","small shoulder pouch","minimal belt hardware","arm warmers","subtle cutout details","micro bag","clean zipper lines","layered straps"]},
  visualkei:{name:"visual kei gothic fashion",sil:["dramatic asymmetric silhouette","narrow gothic silhouette","long layered silhouette","ornate top-heavy silhouette"],
    tops:["asymmetrical gothic jacket","fitted lace-up jacket","cropped military jacket","ruffled high-collar top","ornate fitted coat","strapped gothic vest"],
    bottoms:["layered asymmetric skirt","slim strapped pants","ruffled shorts","long split skirt panels","fitted buckle pants","pleated gothic skirt"],
    shoes:["ornate platform boots","buckled knee-high boots","heavy gothic platforms","pointed platform shoes"],
    extras:["lace cuffs","cross straps","ornate chains","rose charms","decorative buckles","ruffled trim","brooch hardware","long ribbon details"]},
  rave:{name:"cyber rave fashion",sil:["high-energy layered silhouette","wide-leg rave silhouette","cropped utility silhouette","oversized club silhouette"],
    tops:["cropped rave jacket","mesh technical top","reflective utility vest","strapped halter top","oversized club hoodie","panelled shell jacket"],
    bottoms:["extra-wide rave pants","strapped cargo shorts","reflective mini skirt","baggy utility trousers","layered club skirt","wide-leg track pants"],
    shoes:["massive rave sneakers","platform club boots","chunky technical trainers","oversized platform shoes"],
    extras:["glow-stick straps","reflective tape details","utility clips","arm bands","device pouch","cable accessories","ring hardware","wrist cuffs"]}
};

const secondaryCompat = {
  y2k:["soft","cyber","sport","webcore","animal","mcbling","acubi"],
  soft:["y2k","animal","winter","doll","acubi"],
  cyber:["y2k","metal","angel","webcore","sport","rave","acubi"],
  metal:["cyber","angel","doll","visualkei","rave"],
  aviator:["winter","animal","y2k","rave"],
  animal:["soft","winter","y2k","aviator"],
  angel:["cyber","metal","doll","visualkei"],
  doll:["soft","metal","angel","visualkei","mcbling"],
  webcore:["cyber","y2k","sport","rave"],
  winter:["aviator","animal","soft","acubi"],
  sport:["y2k","cyber","webcore","rave","mcbling"],
  mcbling:["y2k","sport","doll","acubi"],
  acubi:["y2k","soft","cyber","winter","mcbling"],
  visualkei:["metal","doll","angel"],
  rave:["cyber","webcore","sport","metal","aviator"]
};

const heroMap = {
  none:{icon:"☆",name:"NO HEAD PIECE",tag:null,sub:"clean head silhouette",styles:["y2k","soft","cyber","metal","aviator","animal","angel","doll","webcore","winter","sport","mcbling","acubi","visualkei","rave"]},
  headset:{icon:"🎧",name:"HEADSET",tag:"oversized futuristic headset",sub:"audio statement head accessory",styles:["y2k","cyber","webcore","sport","metal","mcbling","rave"]},
  hood:{icon:"☁",name:"ANIMAL HOOD",tag:"oversized animal ear hood",sub:"soft head silhouette",styles:["animal","soft","winter","y2k","aviator"]},
  goggles:{icon:"🥽",name:"GOGGLES",tag:"large pilot goggles",sub:"retro technical head accessory",styles:["aviator","winter","cyber","y2k","rave"]},
  halo:{icon:"😇",name:"HALO",tag:"mechanical halo",sub:"floating head ornament",styles:["angel","cyber","metal","doll","visualkei"]},
  horns:{icon:"😈",name:"HORNS",tag:"decorative horns",sub:"gothic head silhouette",styles:["metal","visualkei","doll","angel","cyber"]},
  visor:{icon:"🕶️",name:"VISOR",tag:"futuristic visor",sub:"technical face and head accessory",styles:["cyber","webcore","sport","rave","acubi"]},
  beanie:{icon:"🧢",name:"BEANIE",tag:"oversized beanie",sub:"casual y2k headwear",styles:["y2k","soft","animal","winter","mcbling","acubi"]},
  wings:{icon:"🪽",name:"HEAD WINGS",tag:"feathered head wings",sub:"winged head silhouette",styles:["angel","doll","visualkei","metal","cyber","mcbling"]}
};

// Back pieces are style-agnostic statement items; "random" is resolved at print time.
const backPieces={
  none:{tag:null},
  angel:{tag:"large angel wings"},
  demon:{tag:"black demon wings"},
  fairy:{tag:"translucent fairy wings"},
  butterfly:{tag:"butterfly wings"},
  mech:{tag:"mechanical wings"},
  waist:{tag:"small wings on waist"},
  cape:{tag:"long flowing cape"}
};

// Per-item detail tags, appended only at COMPLEXITY Max so details never contradict the garment.
const itemDetails={
  // tops
  "oversized zip hoodie":["double zip pulls","drop shoulder seams"],
  "cropped bomber jacket":["ribbed hem band","shoulder zip details"],
  "layered tank top":["double strap layers","raw hem edges"],
  "technical track jacket":["contrast piping","snap chest pocket"],
  "cropped jersey jacket":["numbered sleeve print","striped rib collar"],
  "boxy zip cardigan":["chunky knit texture","oversized buttons"],
  "distressed knit sweater":["frayed hem threads","open weave holes"],
  "oversized cardigan jacket":["deep patch pockets","loose rolled cuffs"],
  "washed zip hoodie":["faded wash texture","drawstring hood"],
  "layered knit top":["contrast underlayer","ribbed neckline"],
  "cropped knit bolero":["scalloped knit edge","tied front closure"],
  "slouchy hooded sweater":["extra long sleeves","slouched hood drape"],
  "cropped technical jacket":["taped seams","cord lock hem"],
  "fitted zip top":["high zip collar","thumbhole cuffs"],
  "structured cyber jacket":["molded shoulder panels","glossy trim lines"],
  "mesh layered top":["sheer mesh sleeves","layered hem lines"],
  "paneled utility top":["stitched panel blocks","utility chest straps"],
  "cropped shell jacket":["packable shell fabric","elastic hem cord"],
  "sculpted gothic bodice":["boned seam lines","sweetheart neckline"],
  "glossy fitted jacket":["patent sheen finish","slim zip lines"],
  "armored corset-inspired top":["plated front panels","side lacing"],
  "structured cutout top":["geometric cutouts","clean bonded edges"],
  "paneled gothic bustier":["laced back panel","structured cups"],
  "cropped armored bolero":["segmented shoulder plates","stiff collar frame"],
  "cropped flight jacket":["patch sleeve badges","ribbed storm cuffs"],
  "distressed flight jacket":["worn leather creases","scuffed elbow patches"],
  "fur-trimmed aviator jacket":["shearling collar","brass front zip"],
  "knit flight layer":["waffle knit body","snap shoulder tab"],
  "oversized bomber vest":["puffed quilt panels","wide armholes"],
  "utility pilot jacket":["arm pen pocket","cargo chest flaps"],
  "oversized animal hoodie":["animal ear hood","paw print cuffs"],
  "fur-trimmed jacket":["plush fur collar","soft brushed lining"],
  "puffy zip jacket":["rounded quilt lines","cloud-like volume"],
  "soft oversized sweater":["brushed fleece knit","dropped shoulder fit"],
  "plush shell jacket":["velvety plush finish","rounded collar"],
  "cropped fluffy hoodie":["fuzzy pile texture","pom drawstrings"],
  "fitted harness top":["crossed harness straps","metal slide adjusters"],
  "structured bolero":["sharp shoulder line","open front frame"],
  "layered zip top":["double zip layers","contrast inner collar"],
  "wing-mount bodice":["back mounting straps","reinforced shoulder seams"],
  "segmented cropped jacket":["articulated seam segments","exposed stitch lines"],
  "corset-inspired bodice":["front busk closure","cinched waist seams"],
  "cropped puff-sleeve jacket":["gathered puff sleeves","fitted cuff bands"],
  "fitted ribbon top":["ribbon lace-up front","bow trimmed straps"],
  "structured doll jacket":["rounded lapels","covered button row"],
  "lace-up cropped top":["side lace-up panels","eyelet trim"],
  "mini bolero jacket":["cropped open front","curved hem line"],
  "oversized graphic hoodie":["large front graphic","kangaroo pocket"],
  "layered mesh zip top":["mesh over jersey","exposed zip tape"],
  "cropped utility jacket":["flap chest pockets","webbing trim"],
  "technical sweatshirt":["bonded seam lines","zip shoulder vent"],
  "window-panel jacket":["clear window panels","boxy squared fit"],
  "boxy track top":["side stripe bands","snap button front"],
  "cropped puffer jacket":["glossy puffer quilting","high padded collar"],
  "oversized insulated jacket":["thick padded body","storm flap zip"],
  "fur-trimmed zip jacket":["fur-lined hood edge","chunky zip pull"],
  "thick knit utility top":["cable knit texture","chest strap detail"],
  "short padded coat":["boxy padded fit","snap front closure"],
  "layered fleece jacket":["fleece pile body","contrast chest panel"],
  "cropped track jacket":["retro sleeve stripes","raised knit collar"],
  "technical jersey top":["perforated side panels","curved hem cut"],
  "zip athletic shell":["lightweight shell fabric","reflective zip line"],
  "short racing jacket":["racing patch details","checkered trim line"],
  "panelled sport hoodie":["colorblock panels","mesh hood lining"],
  "mesh utility top":["utility mesh pockets","reinforced hem tape"],
  "fitted zip jacket":["slim contour seams","matte zip hardware"],
  "cropped faux-fur jacket":["soft faux-fur pile","hook front closure"],
  "rhinestone tank top":["rhinestone lettering","sparkling strap trim"],
  "shrunken track jacket":["extra short fit","tight rib cuffs"],
  "halter-style layered top":["halter neck tie","layered hem points"],
  "short glam cardigan":["glitter knit thread","tiny pearl buttons"],
  "fitted bolero top":["snug arm fit","open chest frame"],
  "cropped zip cardigan":["half-zip collar","fitted rib hem"],
  "layered fitted tank":["double layered straps","contrast hem band"],
  "minimal technical top":["clean seamless front","tonal micro logo"],
  "short shrug jacket":["open shrug cut","gathered sleeve ends"],
  "asymmetrical fitted top":["diagonal hem line","single shoulder strap"],
  "asymmetrical gothic jacket":["offset front zip","uneven hem drape"],
  "fitted lace-up jacket":["laced sleeve seams","corset back lacing"],
  "cropped military jacket":["braided cord trim","stand collar hooks"],
  "ruffled high-collar top":["ruffled collar tiers","puffed shoulder gathers"],
  "ornate fitted coat":["embroidered trim lines","ornate clasp buttons"],
  "strapped gothic vest":["buckled front straps","o-ring details"],
  "cropped rave jacket":["reflective panel strips","glow trim edges"],
  "mesh technical top":["technical mesh weave","bonded logo patch"],
  "reflective utility vest":["reflective tape bands","clip front buckles"],
  "strapped halter top":["multi strap back","o-ring neckline"],
  "oversized club hoodie":["dropped oversized fit","printed sleeve text"],
  "panelled shell jacket":["contrast shell panels","elastic cinch waist"],
  // bottoms
  "baggy cargo pants":["bulging side pockets","drawstring ankle cuffs"],
  "wide cargo shorts":["flap thigh pockets","wide leg openings"],
  "pleated mini skirt":["sharp knife pleats","stitched waistband"],
  "low-rise wide jeans":["faded denim wash","wide straight legs"],
  "layered shorts":["double layer hems","contrast underlayer"],
  "utility mini skirt":["side utility pockets","belt loop details"],
  "layered mini skirt":["tiered hem layers","contrast trim edge"],
  "loose shorts":["relaxed drape fit","elastic waistband"],
  "wide distressed pants":["ripped knee patches","frayed hem edges"],
  "pleated skirt":["deep even pleats","clean waist seam"],
  "scrunched shorts":["ruched side seams","gathered hem bands"],
  "soft utility skirt":["soft brushed fabric","snap cargo pocket"],
  "strapped cargo pants":["dangling side straps","buckle knee bands"],
  "asymmetrical mini skirt":["angled hem cut","offset front slit"],
  "technical shorts":["zip vent seams","bonded waistband"],
  "wide utility pants":["multi tool pockets","reinforced knee panels"],
  "modular skirt panels":["detachable panel snaps","overlapping plates"],
  "low-rise tech trousers":["articulated knee darts","zip ankle gussets"],
  "asymmetrical strapped skirt":["cross strap overlay","uneven layered hem"],
  "fitted shorts with harness straps":["thigh harness bands","metal clip rings"],
  "layered armor skirt":["plated skirt segments","riveted edges"],
  "low-rise strapped pants":["hanging belt straps","chained side loops"],
  "ring-belt mini skirt":["large o-ring belt","stitched hem border"],
  "paneled gothic shorts":["laced side panels","buckle waist tabs"],
  "loose aviation pants":["zip cargo thighs","strap cinched ankles"],
  "cargo shorts":["boxy cargo pockets","rolled hem cuffs"],
  "utility trousers":["tool loop waist","double seat stitching"],
  "strapped flight pants":["harness leg straps","flight zip pockets"],
  "thick cuff shorts":["wide folded cuffs","heavy twill weave"],
  "baggy shorts":["extra wide fit","deep slouch pockets"],
  "rounded mini skirt":["curved bubble shape","soft rounded hem"],
  "loose cargo pants":["slouched pocket drape","tapered drawcord hems"],
  "puffy skirt":["padded quilt volume","puffed rounded hem"],
  "soft cuff trousers":["ribbed soft cuffs","relaxed straight fit"],
  "strapped shorts":["side buckle straps","ring belt loops"],
  "fitted cargo pants":["slim cargo pockets","stretch panel knees"],
  "layered skirt":["stacked fabric tiers","peek underlayer"],
  "floating panel skirt":["suspended fabric panels","open side gaps"],
  "ring-linked shorts":["chain ring links","metal grommet hem"],
  "bubble skirt":["gathered bubble hem","voluminous silhouette"],
  "pleated strapped skirt":["pleats with straps","clip hardware details"],
  "fitted shorts":["clean fitted cut","minimal seam lines"],
  "tiered skirt":["three stacked tiers","gathered seam rows"],
  "garter-linked mini skirt":["garter clip straps","lace trim edge"],
  "baggy utility pants":["oversized leg pockets","cinched waist cord"],
  "wide shorts":["squared wide hem","flat front seam"],
  "pixel-pocket trousers":["squared pixel pockets","blocky stitched seams"],
  "paneled shorts":["colorblock panels","contrast stitching"],
  "baggy winter cargo pants":["insulated thick fabric","snow gaiter cuffs"],
  "padded shorts":["quilted padding","puffed leg bands"],
  "thick cuff trousers":["heavy rolled cuffs","brushed warm lining"],
  "layered winter shorts":["shorts over leggings","fleece trim hem"],
  "strap cargo skirt":["cargo pocket front","dangling strap ends"],
  "track shorts":["side stripe trim","curved split hem"],
  "low-rise cargo pants":["hip-slung waistband","roomy cargo pouches"],
  "sport mini skirt":["built-in short liner","contrast side piping"],
  "paneled jogger pants":["curved panel seams","ribbed jogger cuffs"],
  "fitted utility shorts":["zip utility pockets","belted waist tabs"],
  "wide track pants":["snap side buttons","loose track drape"],
  "low-rise flared pants":["flared hem sweep","hip hugging waist"],
  "micro pleated skirt":["tiny dense pleats","micro mini length"],
  "wide velour pants":["plush velour sheen","embroidered back detail"],
  "denim mini skirt":["contrast topstitching","frayed denim hem"],
  "low-rise cargo skirt":["hip pocket flaps","belted low waist"],
  "low-rise straight pants":["clean straight legs","minimal flat front"],
  "fitted cargo skirt":["slim fit cargo pockets","back slit hem"],
  "slim utility trousers":["narrow tool pockets","tapered clean line"],
  "straight cargo pants":["knee flap pockets","even straight cut"],
  "layered asymmetric skirt":["draped uneven layers","pointed hem tips"],
  "slim strapped pants":["slim buckle straps","zip ankle cuffs"],
  "ruffled shorts":["ruffle trimmed hems","gathered waist frill"],
  "long split skirt panels":["thigh-high splits","flowing long panels"],
  "fitted buckle pants":["rows of buckles","fitted stretch weave"],
  "pleated gothic skirt":["lace underlay","chain trim edge"],
  "extra-wide rave pants":["floor-sweeping width","glow seam piping"],
  "strapped cargo shorts":["clip-on strap webbing","boxy cargo flaps"],
  "reflective mini skirt":["light-reflective panels","glossy hem trim"],
  "baggy utility trousers":["slouchy utility fit","carabiner belt loop"],
  "layered club skirt":["mesh over satin layers","uneven club hem"],
  "wide-leg track pants":["wide stripe legs","elastic drawcord waist"],
  // shoes
  "chunky platform sneakers":["stacked foam sole","chunky lace loops"],
  "oversized sneakers":["exaggerated bulky tongue","thick rounded toe"],
  "platform skate shoes":["flat grip sole","padded skate collar"],
  "thick sole trainers":["double stacked sole","cushioned heel unit"],
  "heavy platform shoes":["towering block sole","reinforced toe cap"],
  "scrunched leg warmer boots":["slouched knit shafts","soft scrunch folds"],
  "chunky sneakers":["layered sole panels","padded high tongue"],
  "soft platform boots":["cushioned round sole","plush inner lining"],
  "futuristic platform sneakers":["sculpted sole ridges","glossy panel accents"],
  "knee-high technical boots":["zip side closures","strapped shaft bands"],
  "heavy platform boots":["deep lug tread","tall sole stack"],
  "segmented sole sneakers":["split segment tread","visible sole joints"],
  "massive platform boots":["extreme sole height","wide stable base"],
  "heavy combat platform boots":["combat lace hooks","steel toe look"],
  "knee-high futuristic boots":["seamless molded shaft","angular heel block"],
  "armored platform shoes":["plated toe guards","riveted side panels"],
  "aviator boots":["shearling lined tops","buckle side straps"],
  "heavy winter boots":["insulated thick lining","gripped snow tread"],
  "chunky utility boots":["utility strap buckles","lugged rubber sole"],
  "thick pilot boots":["fleece rolled collar","sturdy flight sole"],
  "oversized plush boots":["fluffy plush exterior","rounded puffy shape"],
  "thick winter boots":["padded ankle collar","weatherproof shell"],
  "rounded platform shoes":["bubble rounded sole","smooth curved toe"],
  "platform boots":["even platform rise","clean shaft line"],
  "futuristic knee boots":["glossy molded surface","hidden zip seam"],
  "angular platform shoes":["sharp angled sole","geometric heel cut"],
  "segmented high boots":["articulated shaft plates","jointed ankle flex"],
  "doll platform boots":["rounded doll toe","ribbon lace ties"],
  "thick buckle shoes":["oversized strap buckle","sturdy block heel"],
  "knee-high platform boots":["full-length side zip","platform lift sole"],
  "chunky tech sneakers":["cage lace system","tech panel overlays"],
  "platform sneakers":["classic platform lift","clean rubber sidewall"],
  "utility boots":["speed lace hooks","tough stitched welt"],
  "retro runner platforms":["retro wave panels","gum-look sole"],
  "oversized winter boots":["puffy insulated shell","toggle cord locks"],
  "fur-lined platform boots":["fur cuff tops","warm lined shaft"],
  "chunky snow boots":["snow collar cinch","deep winter tread"],
  "thick utility boots":["double stitched seams","heavy duty eyelets"],
  "chunky running platforms":["curved rocker sole","breathable mesh panels"],
  "technical sneakers":["engineered knit upper","printed tech details"],
  "oversized trainers":["bulky padded collar","wide flared sole"],
  "sport platform shoes":["springy platform foam","sporty side stripes"],
  "chunky glam boots":["glitter panel shine","chunky sculpted heel"],
  "minimal platform sneakers":["clean minimal upper","tonal flat laces"],
  "slim technical boots":["slim zip profile","matte technical finish"],
  "chunky low-profile sneakers":["low bulky silhouette","rounded wide fit"],
  "platform loafers":["polished loafer strap","stacked lug sole"],
  "ornate platform boots":["engraved metal accents","embossed shaft pattern"],
  "buckled knee-high boots":["rows of shaft buckles","adjustable strap fit"],
  "heavy gothic platforms":["gothic ring straps","massive tread base"],
  "pointed platform shoes":["pointed toe line","sleek platform wedge"],
  "massive rave sneakers":["giant layered sole","glow accent panels"],
  "platform club boots":["shiny club sheen","zip back closure"],
  "chunky technical trainers":["modular panel build","rugged trail sole"],
  "oversized platform shoes":["extra wide sole flare","padded bulky upper"]
};

const animals={
  rabbit:["rabbit themed outfit","long drooping proportions"],
  cat:["cat themed outfit","slim sharp proportions"],
  dog:["dog themed outfit","loose heavy proportions"],
  hamster:["hamster themed outfit","round compact proportions"],
  bear:["bear themed outfit","bulky cozy proportions"]
};

const customAnimalNames=[
  {en:"fox",ko:"여우"},{en:"sheep",ko:"양"},{en:"mouse",ko:"생쥐"},{en:"deer",ko:"사슴"},{en:"wolf",ko:"늑대"},
  {en:"otter",ko:"수달"},{en:"raccoon",ko:"너구리"},{en:"bat",ko:"박쥐"},{en:"bunny",ko:"아기 토끼"},{en:"panda",ko:"판다"}
];
// OTHER-only schema. Similar motifs stay distinct when their placement or role differs.
const shuffleAddOns=[
  {tag:"back-mounted fabric wings",ko:"등에 다는 천 날개",role:"back"},
  {tag:"wing-shaped hair clips",ko:"날개 모양 머리핀",role:"head"},
  {tag:"asymmetric hip tassels",ko:"비대칭 허리 태슬",role:"waist"},
  {tag:"transparent vinyl pockets",ko:"투명 비닐 주머니",role:"garment"},
  {tag:"oversized safety-pin jewelry",ko:"대형 옷핀 장신구",role:"jewelry"},
  {tag:"detachable sleeve panels",ko:"탈착식 소매 패널",role:"arms"},
  {tag:"layered waist drapes",ko:"겹친 허리 드레이프",role:"waist"},
  {tag:"decorative carabiner cluster",ko:"장식용 카라비너 묶음",role:"hardware"},
  {tag:"shoulder capelet",ko:"어깨 케이프",role:"shoulders"},
  {tag:"body chain jewelry",ko:"바디 체인 장신구",role:"body"}
];

const legwear=["leg warmers","thigh straps","loose socks","striped socks","garter straps","knee straps","layered stockings","scrunched socks","mesh leg panels"];
const specials=["small feathered wings","mechanical wings","holographic wing panels","floating segmented ornaments","cyber tail","plush charm keychain","mini disc player accessory","star-shaped hardware","heart-shaped hardware","flip phone charm","tamagotchi-style keychain","folder-shaped charm","mini mp3 player"];
