// Prompt Archive 2004 - outfit data and compatibility rules
const styles = {
  y2k:{name:"y2k streetwear",sil:["baggy layered silhouette","cropped top-heavy silhouette","relaxed low-rise silhouette","slim sporty silhouette"],
    tops:["oversized zip hoodie","cropped bomber jacket","layered tank top","technical track jacket","cropped jersey jacket","boxy zip cardigan"],
    bottoms:["baggy cargo pants","wide cargo shorts","pleated mini skirt","low-rise wide jeans","layered shorts","utility mini skirt"],
    shoes:["chunky platform sneakers","oversized sneakers","platform skate shoes","thick sole trainers"],
    extras:["crossbody pouch","hanging belt straps","arm warmers","double belt","zipper details","star charms","mini shoulder bag","wallet chain"]},
  soft:{name:"soft grunge fashion",sil:["drooping layered silhouette","slouchy oversized silhouette","soft compact silhouette","long cozy silhouette"],
    tops:["distressed knit sweater","oversized cardigan jacket","washed zip hoodie","layered knit top","cropped knit bolero","slouchy hooded sweater"],
    bottoms:["layered mini skirt","loose shorts","wide distressed pants","pleated skirt","scrunched shorts","soft utility skirt"],
    shoes:["heavy platform shoes","scrunched leg warmer boots","chunky sneakers","soft platform boots"],
    extras:["chain charms","loose socks","leg warmers","mini shoulder bag","stitched details","safety pin accents","fabric straps","tiny heart hardware"]},
  cyber:{name:"cyber y2k streetwear",sil:["sharp cropped silhouette","technical baggy silhouette","fitted top-heavy silhouette","segmented layered silhouette"],
    tops:["cropped technical jacket","fitted zip top","structured cyber jacket","mesh layered top","paneled utility top","cropped shell jacket"],
    bottoms:["strapped cargo pants","asymmetrical mini skirt","technical shorts","wide utility pants","modular skirt panels","low-rise tech trousers"],
    shoes:["futuristic platform sneakers","knee-high technical boots","heavy platform boots","segmented sole sneakers"],
    extras:["cable details","utility straps","metal rings","micro pouches","visor hardware","clip fasteners","device holster","clear panel accents"]},
  metal:{name:"metallic cyber gothic fashion",sil:["sharp fitted silhouette","armored top-heavy silhouette","sculpted asymmetric silhouette","heavy lower-body silhouette"],
    tops:["sculpted gothic bodice","glossy fitted jacket","armored corset-inspired top","structured cutout top","paneled gothic bustier","cropped armored bolero"],
    bottoms:["asymmetrical strapped skirt","fitted shorts with harness straps","layered armor skirt","low-rise strapped pants","ring-belt mini skirt","paneled gothic shorts"],
    shoes:["massive platform boots","heavy combat platform boots","knee-high futuristic boots","armored platform shoes"],
    extras:["ring hardware","chain harness","spiked details","metal plates","oversized buckles","industrial clips","segmented armor pieces","body straps"]},
  aviator:{name:"aviator streetwear",sil:["bulky cropped flight silhouette","cozy utility silhouette","relaxed layered silhouette","top-heavy pilot silhouette"],
    tops:["cropped flight jacket","distressed flight jacket","fur-trimmed aviator jacket","knit flight layer","oversized bomber vest","utility pilot jacket"],
    bottoms:["loose aviation pants","cargo shorts","utility trousers","layered shorts","strapped flight pants","thick cuff shorts"],
    shoes:["aviator boots","heavy winter boots","chunky utility boots","thick pilot boots"],
    extras:["pilot straps","utility belt","crossbody map pouch","fingerless gloves","buckle details","patch pockets","flight harness","long belt tails"]},
  animal:{name:"plush animal streetwear",sil:["puffy compact silhouette","oversized cozy silhouette","long drooping silhouette","rounded layered silhouette"],
    tops:["oversized animal hoodie","fur-trimmed jacket","puffy zip jacket","soft oversized sweater","plush shell jacket","cropped fluffy hoodie"],
    bottoms:["baggy shorts","rounded mini skirt","loose cargo pants","layered shorts","puffy skirt","soft cuff trousers"],
    shoes:["oversized plush boots","chunky sneakers","thick winter boots","rounded platform shoes"],
    extras:["plush pouch","fluffy leg warmers","soft mittens","dangling charms","stitched details","paw-shaped pouch","round utility bag","soft straps"]},
  angel:{name:"cyber angel streetwear",sil:["sleek fitted silhouette","floating layered silhouette","sharp asymmetric silhouette","light top-heavy silhouette"],
    tops:["fitted harness top","cropped technical jacket","structured bolero","layered zip top","wing-mount bodice","segmented cropped jacket"],
    bottoms:["asymmetrical mini skirt","strapped shorts","fitted cargo pants","layered skirt","floating panel skirt","ring-linked shorts"],
    shoes:["platform boots","futuristic knee boots","angular platform shoes","segmented high boots"],
    extras:["back harness","floating ornaments","metal rings","thigh straps","transparent details","star hardware","segmented straps","waist clips"]},
  doll:{name:"cyber doll gothic fashion",sil:["compact doll silhouette","fitted waist silhouette","puffy top-balanced silhouette","rounded skirt silhouette"],
    tops:["corset-inspired bodice","cropped puff-sleeve jacket","fitted ribbon top","structured doll jacket","lace-up cropped top","mini bolero jacket"],
    bottoms:["layered mini skirt","bubble skirt","pleated strapped skirt","fitted shorts","tiered skirt","garter-linked mini skirt"],
    shoes:["doll platform boots","thick buckle shoes","knee-high platform boots","rounded platform shoes"],
    extras:["oversized bows","garter straps","heart hardware","lace details","miniature charms","ribbon belts","tiny lock charms","frill trim"]},
  webcore:{name:"webcore fashion",sil:["graphic baggy silhouette","tech layered silhouette","compact digital silhouette","boxy screen-inspired silhouette"],
    tops:["oversized graphic hoodie","layered mesh zip top","cropped utility jacket","technical sweatshirt","window-panel jacket","boxy track top"],
    bottoms:["baggy utility pants","wide shorts","layered mini skirt","strapped cargo pants","pixel-pocket trousers","paneled shorts"],
    shoes:["chunky tech sneakers","platform sneakers","utility boots","retro runner platforms"],
    extras:["digital charms","cable straps","pixel accessories","mini device pouch","glitch motifs","screen-shaped pouch","disc charm","folder-shaped bag"]},
  winter:{name:"winter utility streetwear",sil:["bulky layered winter silhouette","soft oversized silhouette","heavy bottom silhouette","compact insulated silhouette"],
    tops:["cropped puffer jacket","oversized insulated jacket","fur-trimmed zip jacket","thick knit utility top","short padded coat","layered fleece jacket"],
    bottoms:["baggy winter cargo pants","padded shorts","utility mini skirt","thick cuff trousers","layered winter shorts","strap cargo skirt"],
    shoes:["oversized winter boots","fur-lined platform boots","chunky snow boots","thick utility boots"],
    extras:["thick leg warmers","padded gloves","utility pouch","wide scarf","buckle straps","soft harness","thermal sleeves","mini thermos pouch"]},
  sport:{name:"sport tech y2k fashion",sil:["athletic fitted silhouette","sporty oversized silhouette","cropped technical silhouette","balanced track silhouette"],
    tops:["cropped track jacket","technical jersey top","zip athletic shell","short racing jacket","panelled sport hoodie","mesh utility top"],
    bottoms:["track shorts","low-rise cargo pants","sport mini skirt","paneled jogger pants","fitted utility shorts","wide track pants"],
    shoes:["chunky running platforms","technical sneakers","oversized trainers","sport platform shoes"],
    extras:["wrist bands","utility clips","micro sport bag","zip details","number patches","headband accessory","sport straps","device pouch"]},
  mcbling:{name:"mcbling y2k fashion",sil:["fitted glam silhouette","tiny-top wide-bottom silhouette","cropped diva silhouette","low-rise flashy silhouette"],
    tops:["fitted zip jacket","cropped faux-fur jacket","rhinestone tank top","shrunken track jacket","halter-style layered top","short glam cardigan"],
    bottoms:["low-rise flared pants","micro pleated skirt","wide velour pants","fitted shorts","denim mini skirt","low-rise cargo skirt"],
    shoes:["platform sneakers","chunky glam boots","thick sole trainers","knee-high platform boots"],
    extras:["rhinestone details","heart charm belt","mini shoulder bag","phone charm","glossy hardware","oversized sunglasses accessory","chain belt","star jewelry"]},
  acubi:{name:"acubi tech fashion",sil:["minimal fitted silhouette","slim layered silhouette","cropped clean silhouette","narrow technical silhouette"],
    tops:["fitted bolero top","cropped zip cardigan","layered fitted tank","minimal technical top","short shrug jacket","asymmetrical fitted top"],
    bottoms:["low-rise straight pants","fitted cargo skirt","slim utility trousers","layered mini skirt","straight cargo pants","fitted shorts"],
    shoes:["minimal platform sneakers","slim technical boots","chunky low-profile sneakers","platform loafers"],
    extras:["thin utility straps","small shoulder pouch","minimal belt hardware","arm warmers","subtle cutout details","micro bag","clean zipper lines","layered straps"]},
  visualkei:{name:"visual kei gothic fashion",sil:["dramatic asymmetric silhouette","narrow gothic silhouette","long layered silhouette","ornate top-heavy silhouette"],
    tops:["asymmetrical gothic jacket","fitted lace-up jacket","cropped military jacket","ruffled high-collar top","ornate fitted coat","strapped gothic vest"],
    bottoms:["layered asymmetric skirt","slim strapped pants","ruffled shorts","long split skirt panels","fitted buckle pants","pleated gothic skirt"],
    shoes:["ornate platform boots","buckled knee-high boots","heavy gothic platforms","pointed platform shoes"],
    extras:["lace cuffs","cross straps","ornate chains","rose charms","decorative buckles","ruffled trim","brooch hardware","long ribbon details"]},
  rave:{name:"cyber rave fashion",sil:["high-energy layered silhouette","wide-leg rave silhouette","cropped utility silhouette","oversized club silhouette"],
    tops:["cropped rave jacket","mesh technical top","reflective utility vest","strapped halter top","oversized club hoodie","panelled shell jacket"],
    bottoms:["extra-wide rave pants","strapped cargo shorts","reflective mini skirt","baggy utility trousers","layered club skirt","wide-leg track pants"],
    shoes:["massive rave sneakers","platform club boots","chunky technical trainers","oversized platform shoes"],
    extras:["glow-stick straps","reflective tape details","utility clips","arm bands","device pouch","cable accessories","ring hardware","wrist cuffs"]}
};

const secondaryCompat = {
  y2k:["soft","cyber","sport","webcore","animal","mcbling","acubi"],
  soft:["y2k","animal","winter","doll","acubi"],
  cyber:["y2k","metal","angel","webcore","sport","rave","acubi"],
  metal:["cyber","angel","doll","visualkei","rave"],
  aviator:["winter","animal","y2k","rave"],
  animal:["soft","winter","y2k","aviator"],
  angel:["cyber","metal","doll","visualkei"],
  doll:["soft","metal","angel","visualkei","mcbling"],
  webcore:["cyber","y2k","sport","rave"],
  winter:["aviator","animal","soft","acubi"],
  sport:["y2k","cyber","webcore","rave","mcbling"],
  mcbling:["y2k","sport","doll","acubi"],
  acubi:["y2k","soft","cyber","winter","mcbling"],
  visualkei:["metal","doll","angel"],
  rave:["cyber","webcore","sport","metal","aviator"]
};

const heroMap = {
  none:{icon:"☆",name:"NO HEAD PIECE",tag:null,sub:"clean head silhouette",styles:["y2k","soft","cyber","metal","aviator","animal","angel","doll","webcore","winter","sport","mcbling","acubi","visualkei","rave"]},
  headset:{icon:"🎧",name:"HEADSET MODE",tag:"oversized futuristic headset",sub:"audio statement head accessory",styles:["y2k","cyber","webcore","sport","metal","mcbling","rave"]},
  hood:{icon:"☁",name:"ANIMAL HOOD",tag:"oversized animal ear hood",sub:"soft head silhouette",styles:["animal","soft","winter","y2k","aviator"]},
  goggles:{icon:"◉",name:"GOGGLE MODE",tag:"large pilot goggles",sub:"retro technical head accessory",styles:["aviator","winter","cyber","y2k","rave"]},
  halo:{icon:"◎",name:"HALO MODE",tag:"mechanical halo",sub:"floating head ornament",styles:["angel","cyber","metal","doll","visualkei"]},
  horns:{icon:"♈",name:"HORN MODE",tag:"decorative horns",sub:"gothic head silhouette",styles:["metal","visualkei","doll","angel","cyber"]},
  visor:{icon:"▰",name:"VISOR MODE",tag:"futuristic visor",sub:"technical face and head accessory",styles:["cyber","webcore","sport","rave","acubi"]},
  beanie:{icon:"●",name:"BEANIE MODE",tag:"oversized beanie",sub:"casual y2k headwear",styles:["y2k","soft","animal","winter","mcbling","acubi"]}
};

const animals={
  rabbit:["rabbit themed outfit","long drooping proportions"],
  cat:["cat themed outfit","slim sharp proportions"],
  dog:["dog themed outfit","loose heavy proportions"],
  hamster:["hamster themed outfit","round compact proportions"],
  bear:["bear themed outfit","bulky cozy proportions"]
};

const legwear=["leg warmers","thigh straps","loose socks","striped socks","garter straps","knee straps","layered stockings","scrunched socks","mesh leg panels"];
const specials=["small feathered wings","mechanical wings","holographic wing panels","floating segmented ornaments","cyber tail","plush charm keychain","mini disc player accessory","star-shaped hardware","heart-shaped hardware","flip phone charm","tamagotchi-style keychain","folder-shaped charm","mini mp3 player"];
